// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module forward_forward_Pipeline_VITIS_LOOP_44_3 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        v30_load,
        m_axi_gmem_AWVALID,
        m_axi_gmem_AWREADY,
        m_axi_gmem_AWADDR,
        m_axi_gmem_AWID,
        m_axi_gmem_AWLEN,
        m_axi_gmem_AWSIZE,
        m_axi_gmem_AWBURST,
        m_axi_gmem_AWLOCK,
        m_axi_gmem_AWCACHE,
        m_axi_gmem_AWPROT,
        m_axi_gmem_AWQOS,
        m_axi_gmem_AWREGION,
        m_axi_gmem_AWUSER,
        m_axi_gmem_WVALID,
        m_axi_gmem_WREADY,
        m_axi_gmem_WDATA,
        m_axi_gmem_WSTRB,
        m_axi_gmem_WLAST,
        m_axi_gmem_WID,
        m_axi_gmem_WUSER,
        m_axi_gmem_ARVALID,
        m_axi_gmem_ARREADY,
        m_axi_gmem_ARADDR,
        m_axi_gmem_ARID,
        m_axi_gmem_ARLEN,
        m_axi_gmem_ARSIZE,
        m_axi_gmem_ARBURST,
        m_axi_gmem_ARLOCK,
        m_axi_gmem_ARCACHE,
        m_axi_gmem_ARPROT,
        m_axi_gmem_ARQOS,
        m_axi_gmem_ARREGION,
        m_axi_gmem_ARUSER,
        m_axi_gmem_RVALID,
        m_axi_gmem_RREADY,
        m_axi_gmem_RDATA,
        m_axi_gmem_RLAST,
        m_axi_gmem_RID,
        m_axi_gmem_RFIFONUM,
        m_axi_gmem_RUSER,
        m_axi_gmem_RRESP,
        m_axi_gmem_BVALID,
        m_axi_gmem_BREADY,
        m_axi_gmem_BRESP,
        m_axi_gmem_BID,
        m_axi_gmem_BUSER,
        v29_address0,
        v29_ce0,
        v29_q0,
        add_ln46,
        zext_ln44,
        v18_out,
        v18_out_ap_vld,
        grp_fu_380_p_din0,
        grp_fu_380_p_din1,
        grp_fu_380_p_opcode,
        grp_fu_380_p_dout0,
        grp_fu_380_p_ce
);

parameter    ap_ST_fsm_pp0_stage0 = 7'd1;
parameter    ap_ST_fsm_pp0_stage1 = 7'd2;
parameter    ap_ST_fsm_pp0_stage2 = 7'd4;
parameter    ap_ST_fsm_pp0_stage3 = 7'd8;
parameter    ap_ST_fsm_pp0_stage4 = 7'd16;
parameter    ap_ST_fsm_pp0_stage5 = 7'd32;
parameter    ap_ST_fsm_pp0_stage6 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] v30_load;
output   m_axi_gmem_AWVALID;
input   m_axi_gmem_AWREADY;
output  [63:0] m_axi_gmem_AWADDR;
output  [0:0] m_axi_gmem_AWID;
output  [31:0] m_axi_gmem_AWLEN;
output  [2:0] m_axi_gmem_AWSIZE;
output  [1:0] m_axi_gmem_AWBURST;
output  [1:0] m_axi_gmem_AWLOCK;
output  [3:0] m_axi_gmem_AWCACHE;
output  [2:0] m_axi_gmem_AWPROT;
output  [3:0] m_axi_gmem_AWQOS;
output  [3:0] m_axi_gmem_AWREGION;
output  [0:0] m_axi_gmem_AWUSER;
output   m_axi_gmem_WVALID;
input   m_axi_gmem_WREADY;
output  [63:0] m_axi_gmem_WDATA;
output  [7:0] m_axi_gmem_WSTRB;
output   m_axi_gmem_WLAST;
output  [0:0] m_axi_gmem_WID;
output  [0:0] m_axi_gmem_WUSER;
output   m_axi_gmem_ARVALID;
input   m_axi_gmem_ARREADY;
output  [63:0] m_axi_gmem_ARADDR;
output  [0:0] m_axi_gmem_ARID;
output  [31:0] m_axi_gmem_ARLEN;
output  [2:0] m_axi_gmem_ARSIZE;
output  [1:0] m_axi_gmem_ARBURST;
output  [1:0] m_axi_gmem_ARLOCK;
output  [3:0] m_axi_gmem_ARCACHE;
output  [2:0] m_axi_gmem_ARPROT;
output  [3:0] m_axi_gmem_ARQOS;
output  [3:0] m_axi_gmem_ARREGION;
output  [0:0] m_axi_gmem_ARUSER;
input   m_axi_gmem_RVALID;
output   m_axi_gmem_RREADY;
input  [63:0] m_axi_gmem_RDATA;
input   m_axi_gmem_RLAST;
input  [0:0] m_axi_gmem_RID;
input  [8:0] m_axi_gmem_RFIFONUM;
input  [0:0] m_axi_gmem_RUSER;
input  [1:0] m_axi_gmem_RRESP;
input   m_axi_gmem_BVALID;
output   m_axi_gmem_BREADY;
input  [1:0] m_axi_gmem_BRESP;
input  [0:0] m_axi_gmem_BID;
input  [0:0] m_axi_gmem_BUSER;
output  [9:0] v29_address0;
output   v29_ce0;
input  [31:0] v29_q0;
input  [63:0] add_ln46;
input  [5:0] zext_ln44;
output  [31:0] v18_out;
output   v18_out_ap_vld;
output  [31:0] grp_fu_380_p_din0;
output  [31:0] grp_fu_380_p_din1;
output  [1:0] grp_fu_380_p_opcode;
input  [31:0] grp_fu_380_p_dout0;
output   grp_fu_380_p_ce;

reg ap_idle;
reg m_axi_gmem_ARVALID;
reg m_axi_gmem_RREADY;
reg v29_ce0;
reg v18_out_ap_vld;

(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_state7_pp0_stage6_iter0;
wire    ap_block_state14_pp0_stage6_iter1;
wire    ap_block_state21_pp0_stage6_iter2;
wire    ap_block_state28_pp0_stage6_iter3;
wire    ap_block_state35_pp0_stage6_iter4;
wire    ap_block_state42_pp0_stage6_iter5;
wire    ap_block_state49_pp0_stage6_iter6;
wire    ap_block_state56_pp0_stage6_iter7;
wire    ap_block_state63_pp0_stage6_iter8;
wire    ap_block_state70_pp0_stage6_iter9;
wire    ap_block_state77_pp0_stage6_iter10;
wire    ap_block_state84_pp0_stage6_iter11;
wire    ap_block_pp0_stage6_subdone;
reg   [0:0] icmp_ln44_reg_305;
reg    ap_condition_exit_pp0_iter0_stage6;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    gmem_blk_n_AR;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1;
reg    gmem_blk_n_R;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state8_pp0_stage0_iter1;
wire    ap_block_state15_pp0_stage0_iter2;
wire    ap_block_state22_pp0_stage0_iter3;
wire    ap_block_state29_pp0_stage0_iter4;
wire    ap_block_state36_pp0_stage0_iter5;
wire    ap_block_state43_pp0_stage0_iter6;
wire    ap_block_state50_pp0_stage0_iter7;
wire    ap_block_state57_pp0_stage0_iter8;
wire    ap_block_state64_pp0_stage0_iter9;
wire    ap_block_state71_pp0_stage0_iter10;
wire    ap_block_state78_pp0_stage0_iter11;
wire    ap_block_state85_pp0_stage0_iter12;
wire    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln44_cast_fu_154_p1;
reg   [63:0] zext_ln44_cast_reg_294;
reg   [10:0] v15_1_reg_299;
reg   [10:0] v15_1_reg_299_pp0_iter1_reg;
reg   [10:0] v15_1_reg_299_pp0_iter2_reg;
reg   [10:0] v15_1_reg_299_pp0_iter3_reg;
reg   [10:0] v15_1_reg_299_pp0_iter4_reg;
reg   [10:0] v15_1_reg_299_pp0_iter5_reg;
reg   [10:0] v15_1_reg_299_pp0_iter6_reg;
reg   [10:0] v15_1_reg_299_pp0_iter7_reg;
reg   [10:0] v15_1_reg_299_pp0_iter8_reg;
reg   [10:0] v15_1_reg_299_pp0_iter9_reg;
wire   [0:0] icmp_ln44_fu_171_p2;
reg   [0:0] icmp_ln44_reg_305_pp0_iter1_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter2_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter3_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter4_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter5_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter6_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter7_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter8_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter9_reg;
reg   [0:0] icmp_ln44_reg_305_pp0_iter10_reg;
reg   [60:0] trunc_ln46_1_reg_309;
wire    ap_block_state2_pp0_stage1_iter0;
reg    ap_block_state2_io;
wire    ap_block_state9_pp0_stage1_iter1;
wire    ap_block_state16_pp0_stage1_iter2;
wire    ap_block_state23_pp0_stage1_iter3;
wire    ap_block_state30_pp0_stage1_iter4;
wire    ap_block_state37_pp0_stage1_iter5;
wire    ap_block_state44_pp0_stage1_iter6;
wire    ap_block_state51_pp0_stage1_iter7;
wire    ap_block_state58_pp0_stage1_iter8;
wire    ap_block_state65_pp0_stage1_iter9;
reg    ap_block_state72_pp0_stage1_iter10;
wire    ap_block_state79_pp0_stage1_iter11;
reg    ap_block_pp0_stage1_11001;
reg   [31:0] v16_reg_325;
reg   [63:0] gmem_addr_read_reg_330;
wire   [31:0] trunc_ln46_2_fu_259_p1;
reg   [31:0] trunc_ln46_2_reg_335;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_state10_pp0_stage2_iter1;
wire    ap_block_state17_pp0_stage2_iter2;
wire    ap_block_state24_pp0_stage2_iter3;
wire    ap_block_state31_pp0_stage2_iter4;
wire    ap_block_state38_pp0_stage2_iter5;
wire    ap_block_state45_pp0_stage2_iter6;
wire    ap_block_state52_pp0_stage2_iter7;
wire    ap_block_state59_pp0_stage2_iter8;
wire    ap_block_state66_pp0_stage2_iter9;
wire    ap_block_state73_pp0_stage2_iter10;
wire    ap_block_state80_pp0_stage2_iter11;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_state11_pp0_stage3_iter1;
wire    ap_block_state18_pp0_stage3_iter2;
wire    ap_block_state25_pp0_stage3_iter3;
wire    ap_block_state32_pp0_stage3_iter4;
wire    ap_block_state39_pp0_stage3_iter5;
wire    ap_block_state46_pp0_stage3_iter6;
wire    ap_block_state53_pp0_stage3_iter7;
wire    ap_block_state60_pp0_stage3_iter8;
wire    ap_block_state67_pp0_stage3_iter9;
wire    ap_block_state74_pp0_stage3_iter10;
wire    ap_block_state81_pp0_stage3_iter11;
wire    ap_block_pp0_stage3_11001;
wire   [31:0] grp_fu_150_p2;
reg   [31:0] v19_reg_345;
wire    ap_block_pp0_stage6_11001;
reg   [31:0] v20_reg_355;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] v15_cast7_fu_251_p1;
wire    ap_block_pp0_stage0;
wire  signed [63:0] sext_ln46_fu_231_p1;
reg   [31:0] v18_fu_88;
reg   [31:0] ap_sig_allocacmp_v18_load;
wire    ap_loop_init;
reg   [10:0] v15_fu_92;
wire   [10:0] add_ln44_fu_241_p2;
reg   [10:0] ap_sig_allocacmp_v15_1;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] grp_fu_150_p1;
wire    ap_block_pp0_stage3;
wire   [9:0] trunc_ln46_fu_177_p1;
wire   [14:0] shl_ln46_2_fu_181_p3;
wire   [12:0] shl_ln46_3_fu_193_p3;
wire   [15:0] zext_ln46_1_fu_201_p1;
wire   [15:0] zext_ln46_fu_189_p1;
wire   [15:0] add_ln46_2_fu_205_p2;
wire   [63:0] zext_ln46_2_fu_211_p1;
wire   [63:0] add_ln46_1_fu_215_p2;
wire    ap_block_pp0_stage6;
wire    ap_block_pp0_stage2;
wire   [63:0] lshr_ln46_fu_255_p2;
reg    grp_fu_146_ce;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_state12_pp0_stage4_iter1;
wire    ap_block_state19_pp0_stage4_iter2;
wire    ap_block_state26_pp0_stage4_iter3;
wire    ap_block_state33_pp0_stage4_iter4;
wire    ap_block_state40_pp0_stage4_iter5;
wire    ap_block_state47_pp0_stage4_iter6;
wire    ap_block_state54_pp0_stage4_iter7;
wire    ap_block_state61_pp0_stage4_iter8;
wire    ap_block_state68_pp0_stage4_iter9;
wire    ap_block_state75_pp0_stage4_iter10;
wire    ap_block_state82_pp0_stage4_iter11;
wire    ap_block_pp0_stage4_11001;
wire    ap_block_state6_pp0_stage5_iter0;
wire    ap_block_state13_pp0_stage5_iter1;
wire    ap_block_state20_pp0_stage5_iter2;
wire    ap_block_state27_pp0_stage5_iter3;
wire    ap_block_state34_pp0_stage5_iter4;
wire    ap_block_state41_pp0_stage5_iter5;
wire    ap_block_state48_pp0_stage5_iter6;
wire    ap_block_state55_pp0_stage5_iter7;
wire    ap_block_state62_pp0_stage5_iter8;
wire    ap_block_state69_pp0_stage5_iter9;
wire    ap_block_state76_pp0_stage5_iter10;
wire    ap_block_state83_pp0_stage5_iter11;
wire    ap_block_pp0_stage5_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_CS_fsm_pp0_stage5;
reg    grp_fu_150_ce;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_condition_exit_pp0_iter11_stage0;
reg    ap_idle_pp0_0to10;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg   [6:0] ap_NS_fsm;
reg    ap_idle_pp0_1to12;
reg    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_block_pp0_stage0_00001;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 7'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 ap_done_reg = 1'b0;
end

forward_fmul_32ns_32ns_32_4_max_dsp_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fmul_32ns_32ns_32_4_max_dsp_1_U6(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(v16_reg_325),
    .din1(grp_fu_150_p1),
    .ce(grp_fu_150_ce),
    .dout(grp_fu_150_p2)
);

forward_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage6),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage6)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter12 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage6_subdone) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= 1'b0;
    end else if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v15_fu_92 <= 11'd0;
    end else if (((icmp_ln44_reg_305 == 1'd0) & (1'b0 == ap_block_pp0_stage6_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        v15_fu_92 <= add_ln44_fu_241_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            v18_fu_88 <= v30_load;
        end else if ((ap_enable_reg_pp0_iter12 == 1'b1)) begin
            v18_fu_88 <= v20_reg_355;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        gmem_addr_read_reg_330 <= m_axi_gmem_RDATA;
        v16_reg_325 <= v29_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln44_reg_305 <= icmp_ln44_fu_171_p2;
        icmp_ln44_reg_305_pp0_iter10_reg <= icmp_ln44_reg_305_pp0_iter9_reg;
        icmp_ln44_reg_305_pp0_iter1_reg <= icmp_ln44_reg_305;
        icmp_ln44_reg_305_pp0_iter2_reg <= icmp_ln44_reg_305_pp0_iter1_reg;
        icmp_ln44_reg_305_pp0_iter3_reg <= icmp_ln44_reg_305_pp0_iter2_reg;
        icmp_ln44_reg_305_pp0_iter4_reg <= icmp_ln44_reg_305_pp0_iter3_reg;
        icmp_ln44_reg_305_pp0_iter5_reg <= icmp_ln44_reg_305_pp0_iter4_reg;
        icmp_ln44_reg_305_pp0_iter6_reg <= icmp_ln44_reg_305_pp0_iter5_reg;
        icmp_ln44_reg_305_pp0_iter7_reg <= icmp_ln44_reg_305_pp0_iter6_reg;
        icmp_ln44_reg_305_pp0_iter8_reg <= icmp_ln44_reg_305_pp0_iter7_reg;
        icmp_ln44_reg_305_pp0_iter9_reg <= icmp_ln44_reg_305_pp0_iter8_reg;
        v15_1_reg_299 <= ap_sig_allocacmp_v15_1;
        v15_1_reg_299_pp0_iter1_reg <= v15_1_reg_299;
        v15_1_reg_299_pp0_iter2_reg <= v15_1_reg_299_pp0_iter1_reg;
        v15_1_reg_299_pp0_iter3_reg <= v15_1_reg_299_pp0_iter2_reg;
        v15_1_reg_299_pp0_iter4_reg <= v15_1_reg_299_pp0_iter3_reg;
        v15_1_reg_299_pp0_iter5_reg <= v15_1_reg_299_pp0_iter4_reg;
        v15_1_reg_299_pp0_iter6_reg <= v15_1_reg_299_pp0_iter5_reg;
        v15_1_reg_299_pp0_iter7_reg <= v15_1_reg_299_pp0_iter6_reg;
        v15_1_reg_299_pp0_iter8_reg <= v15_1_reg_299_pp0_iter7_reg;
        v15_1_reg_299_pp0_iter9_reg <= v15_1_reg_299_pp0_iter8_reg;
        zext_ln44_cast_reg_294[5 : 0] <= zext_ln44_cast_fu_154_p1[5 : 0];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln44_fu_171_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln46_1_reg_309 <= {{add_ln46_1_fu_215_p2[63:3]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln46_2_reg_335 <= trunc_ln46_2_fu_259_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        v19_reg_345 <= grp_fu_150_p2;
        v20_reg_355 <= grp_fu_380_p_dout0;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_305 == 1'd1) & (1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_condition_exit_pp0_iter0_stage6 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage6 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter11 == 1'b1) & (icmp_ln44_reg_305_pp0_iter10_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter11_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter11_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter11_reg == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to10 = 1'b1;
    end else begin
        ap_idle_pp0_0to10 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0))) begin
        ap_idle_pp0_1to12 = 1'b1;
    end else begin
        ap_idle_pp0_1to12 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage6_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_v15_1 = 11'd0;
    end else begin
        ap_sig_allocacmp_v15_1 = v15_fu_92;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter12 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_v18_load = v20_reg_355;
    end else begin
        ap_sig_allocacmp_v18_load = v18_fu_88;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_305 == 1'd0) & (1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        gmem_blk_n_AR = m_axi_gmem_ARREADY;
    end else begin
        gmem_blk_n_AR = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        gmem_blk_n_R = m_axi_gmem_RVALID;
    end else begin
        gmem_blk_n_R = 1'b1;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        grp_fu_146_ce = 1'b1;
    end else begin
        grp_fu_146_ce = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        grp_fu_150_ce = 1'b1;
    end else begin
        grp_fu_150_ce = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln44_reg_305 == 1'd0) & (1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_gmem_ARVALID = 1'b1;
    end else begin
        m_axi_gmem_ARVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        m_axi_gmem_RREADY = 1'b1;
    end else begin
        m_axi_gmem_RREADY = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln44_reg_305_pp0_iter10_reg == 1'd1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v18_out_ap_vld = 1'b1;
    end else begin
        v18_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter10 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        v29_ce0 = 1'b1;
    end else begin
        v29_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if (((ap_idle_pp0_0to10 == 1'b1) & (1'b1 == ap_condition_exit_pp0_iter11_stage0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to12 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln44_fu_241_p2 = (v15_1_reg_299 + 11'd1);

assign add_ln46_1_fu_215_p2 = (zext_ln46_2_fu_211_p1 + add_ln46);

assign add_ln46_2_fu_205_p2 = (zext_ln46_1_fu_201_p1 + zext_ln46_fu_189_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage1_11001 = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)));
end

always @ (*) begin
    ap_block_pp0_stage1_subdone = (((ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_block_state2_io)) | ((ap_enable_reg_pp0_iter10 == 1'b1) & (m_axi_gmem_RVALID == 1'b0)));
end

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage2_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage3_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage4_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage5_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage6_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage1_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage2_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage3_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage4_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage5_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage6_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage1_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage2_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage3_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state26_pp0_stage4_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state27_pp0_stage5_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state28_pp0_stage6_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state29_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_io = ((icmp_ln44_reg_305 == 1'd0) & (m_axi_gmem_ARREADY == 1'b0));
end

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state30_pp0_stage1_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state31_pp0_stage2_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state32_pp0_stage3_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state33_pp0_stage4_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state34_pp0_stage5_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state35_pp0_stage6_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state36_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state37_pp0_stage1_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state38_pp0_stage2_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state39_pp0_stage3_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state40_pp0_stage4_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state41_pp0_stage5_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state42_pp0_stage6_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state43_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state44_pp0_stage1_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state45_pp0_stage2_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state46_pp0_stage3_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state47_pp0_stage4_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state48_pp0_stage5_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state49_pp0_stage6_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state50_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state51_pp0_stage1_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state52_pp0_stage2_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state53_pp0_stage3_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state54_pp0_stage4_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state55_pp0_stage5_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state56_pp0_stage6_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state57_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state58_pp0_stage1_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state59_pp0_stage2_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state60_pp0_stage3_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state61_pp0_stage4_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state62_pp0_stage5_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state63_pp0_stage6_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state64_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state65_pp0_stage1_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state66_pp0_stage2_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state67_pp0_stage3_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state68_pp0_stage4_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state69_pp0_stage5_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage5_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state70_pp0_stage6_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state71_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state72_pp0_stage1_iter10 = (m_axi_gmem_RVALID == 1'b0);
end

assign ap_block_state73_pp0_stage2_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state74_pp0_stage3_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state75_pp0_stage4_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state76_pp0_stage5_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state77_pp0_stage6_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state78_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state79_pp0_stage1_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage6_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state80_pp0_stage2_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state81_pp0_stage3_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state82_pp0_stage4_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state83_pp0_stage5_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state84_pp0_stage6_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state85_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage6;

assign grp_fu_150_p1 = trunc_ln46_2_reg_335;

assign grp_fu_380_p_ce = grp_fu_146_ce;

assign grp_fu_380_p_din0 = ap_sig_allocacmp_v18_load;

assign grp_fu_380_p_din1 = v19_reg_345;

assign grp_fu_380_p_opcode = 2'd0;

assign icmp_ln44_fu_171_p2 = ((ap_sig_allocacmp_v15_1 == 11'd1024) ? 1'b1 : 1'b0);

assign lshr_ln46_fu_255_p2 = gmem_addr_read_reg_330 >> zext_ln44_cast_reg_294;

assign m_axi_gmem_ARADDR = sext_ln46_fu_231_p1;

assign m_axi_gmem_ARBURST = 2'd0;

assign m_axi_gmem_ARCACHE = 4'd0;

assign m_axi_gmem_ARID = 1'd0;

assign m_axi_gmem_ARLEN = 32'd1;

assign m_axi_gmem_ARLOCK = 2'd0;

assign m_axi_gmem_ARPROT = 3'd0;

assign m_axi_gmem_ARQOS = 4'd0;

assign m_axi_gmem_ARREGION = 4'd0;

assign m_axi_gmem_ARSIZE = 3'd0;

assign m_axi_gmem_ARUSER = 1'd0;

assign m_axi_gmem_AWADDR = 64'd0;

assign m_axi_gmem_AWBURST = 2'd0;

assign m_axi_gmem_AWCACHE = 4'd0;

assign m_axi_gmem_AWID = 1'd0;

assign m_axi_gmem_AWLEN = 32'd0;

assign m_axi_gmem_AWLOCK = 2'd0;

assign m_axi_gmem_AWPROT = 3'd0;

assign m_axi_gmem_AWQOS = 4'd0;

assign m_axi_gmem_AWREGION = 4'd0;

assign m_axi_gmem_AWSIZE = 3'd0;

assign m_axi_gmem_AWUSER = 1'd0;

assign m_axi_gmem_AWVALID = 1'b0;

assign m_axi_gmem_BREADY = 1'b0;

assign m_axi_gmem_WDATA = 64'd0;

assign m_axi_gmem_WID = 1'd0;

assign m_axi_gmem_WLAST = 1'b0;

assign m_axi_gmem_WSTRB = 8'd0;

assign m_axi_gmem_WUSER = 1'd0;

assign m_axi_gmem_WVALID = 1'b0;

assign sext_ln46_fu_231_p1 = $signed(trunc_ln46_1_reg_309);

assign shl_ln46_2_fu_181_p3 = {{trunc_ln46_fu_177_p1}, {5'd0}};

assign shl_ln46_3_fu_193_p3 = {{trunc_ln46_fu_177_p1}, {3'd0}};

assign trunc_ln46_2_fu_259_p1 = lshr_ln46_fu_255_p2[31:0];

assign trunc_ln46_fu_177_p1 = ap_sig_allocacmp_v15_1[9:0];

assign v15_cast7_fu_251_p1 = v15_1_reg_299_pp0_iter9_reg;

assign v18_out = v18_fu_88;

assign v29_address0 = v15_cast7_fu_251_p1;

assign zext_ln44_cast_fu_154_p1 = zext_ln44;

assign zext_ln46_1_fu_201_p1 = shl_ln46_3_fu_193_p3;

assign zext_ln46_2_fu_211_p1 = add_ln46_2_fu_205_p2;

assign zext_ln46_fu_189_p1 = shl_ln46_2_fu_181_p3;

always @ (posedge ap_clk) begin
    zext_ln44_cast_reg_294[63:6] <= 58'b0000000000000000000000000000000000000000000000000000000000;
end

endmodule //forward_forward_Pipeline_VITIS_LOOP_44_3
