// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cemit_replaced_macs_1 (
        l_dataA_1_dout,
        l_dataA_1_empty_n,
        l_dataA_1_read,
        l_dataB_1_dout,
        l_dataB_1_empty_n,
        l_dataB_1_read,
        l_sum_1_din,
        l_sum_1_full_n,
        l_sum_1_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [33:0] l_dataA_1_dout;
input   l_dataA_1_empty_n;
output   l_dataA_1_read;
input  [63:0] l_dataB_1_dout;
input   l_dataB_1_empty_n;
output   l_dataB_1_read;
output  [63:0] l_sum_1_din;
input   l_sum_1_full_n;
output   l_sum_1_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    muls_2_U0_ap_start;
wire    muls_2_U0_ap_done;
wire    muls_2_U0_ap_continue;
wire    muls_2_U0_ap_idle;
wire    muls_2_U0_ap_ready;
wire    muls_2_U0_start_out;
wire    muls_2_U0_start_write;
wire    muls_2_U0_l_dataA_1_read;
wire    muls_2_U0_l_dataB_1_read;
wire   [63:0] muls_2_U0_l_mul1_din;
wire    muls_2_U0_l_mul1_write;
wire    adds_3_U0_ap_start;
wire    adds_3_U0_ap_done;
wire    adds_3_U0_ap_continue;
wire    adds_3_U0_ap_idle;
wire    adds_3_U0_ap_ready;
wire    adds_3_U0_l_mul1_read;
wire   [63:0] adds_3_U0_l_sum_1_din;
wire    adds_3_U0_l_sum_1_write;
wire    l_mul_full_n;
wire   [63:0] l_mul_dout;
wire   [1:0] l_mul_num_data_valid;
wire   [1:0] l_mul_fifo_cap;
wire    l_mul_empty_n;
wire   [0:0] start_for_adds_3_U0_din;
wire    start_for_adds_3_U0_full_n;
wire   [0:0] start_for_adds_3_U0_dout;
wire    start_for_adds_3_U0_empty_n;

cemit_replaced_muls_2 muls_2_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(muls_2_U0_ap_start),
    .start_full_n(start_for_adds_3_U0_full_n),
    .ap_done(muls_2_U0_ap_done),
    .ap_continue(muls_2_U0_ap_continue),
    .ap_idle(muls_2_U0_ap_idle),
    .ap_ready(muls_2_U0_ap_ready),
    .start_out(muls_2_U0_start_out),
    .start_write(muls_2_U0_start_write),
    .l_dataA_1_dout(l_dataA_1_dout),
    .l_dataA_1_num_data_valid(3'd0),
    .l_dataA_1_fifo_cap(3'd0),
    .l_dataA_1_empty_n(l_dataA_1_empty_n),
    .l_dataA_1_read(muls_2_U0_l_dataA_1_read),
    .l_dataB_1_dout(l_dataB_1_dout),
    .l_dataB_1_num_data_valid(2'd0),
    .l_dataB_1_fifo_cap(2'd0),
    .l_dataB_1_empty_n(l_dataB_1_empty_n),
    .l_dataB_1_read(muls_2_U0_l_dataB_1_read),
    .l_mul1_din(muls_2_U0_l_mul1_din),
    .l_mul1_num_data_valid(l_mul_num_data_valid),
    .l_mul1_fifo_cap(l_mul_fifo_cap),
    .l_mul1_full_n(l_mul_full_n),
    .l_mul1_write(muls_2_U0_l_mul1_write)
);

cemit_replaced_adds_3 adds_3_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(adds_3_U0_ap_start),
    .ap_done(adds_3_U0_ap_done),
    .ap_continue(adds_3_U0_ap_continue),
    .ap_idle(adds_3_U0_ap_idle),
    .ap_ready(adds_3_U0_ap_ready),
    .l_mul1_dout(l_mul_dout),
    .l_mul1_num_data_valid(l_mul_num_data_valid),
    .l_mul1_fifo_cap(l_mul_fifo_cap),
    .l_mul1_empty_n(l_mul_empty_n),
    .l_mul1_read(adds_3_U0_l_mul1_read),
    .l_sum_1_din(adds_3_U0_l_sum_1_din),
    .l_sum_1_num_data_valid(2'd0),
    .l_sum_1_fifo_cap(2'd0),
    .l_sum_1_full_n(l_sum_1_full_n),
    .l_sum_1_write(adds_3_U0_l_sum_1_write)
);

cemit_replaced_fifo_w64_d2_S_x l_mul_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(muls_2_U0_l_mul1_din),
    .if_full_n(l_mul_full_n),
    .if_write(muls_2_U0_l_mul1_write),
    .if_dout(l_mul_dout),
    .if_num_data_valid(l_mul_num_data_valid),
    .if_fifo_cap(l_mul_fifo_cap),
    .if_empty_n(l_mul_empty_n),
    .if_read(adds_3_U0_l_mul1_read)
);

cemit_replaced_start_for_adds_3_U0 start_for_adds_3_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_adds_3_U0_din),
    .if_full_n(start_for_adds_3_U0_full_n),
    .if_write(muls_2_U0_start_write),
    .if_dout(start_for_adds_3_U0_dout),
    .if_empty_n(start_for_adds_3_U0_empty_n),
    .if_read(adds_3_U0_ap_ready)
);

assign adds_3_U0_ap_continue = ap_continue;

assign adds_3_U0_ap_start = start_for_adds_3_U0_empty_n;

assign ap_done = adds_3_U0_ap_done;

assign ap_idle = (muls_2_U0_ap_idle & adds_3_U0_ap_idle);

assign ap_ready = muls_2_U0_ap_ready;

assign l_dataA_1_read = muls_2_U0_l_dataA_1_read;

assign l_dataB_1_read = muls_2_U0_l_dataB_1_read;

assign l_sum_1_din = adds_3_U0_l_sum_1_din;

assign l_sum_1_write = adds_3_U0_l_sum_1_write;

assign muls_2_U0_ap_continue = 1'b1;

assign muls_2_U0_ap_start = ap_start;

assign start_for_adds_3_U0_din = 1'b1;

endmodule //cemit_replaced_macs_1
