// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module cemit_replaced_process_r (
        l_strA7_dout,
        l_strA7_empty_n,
        l_strA7_read,
        l_strB8_dout,
        l_strB8_empty_n,
        l_strB8_read,
        l_sum3_din,
        l_sum3_full_n,
        l_sum3_write,
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_ready,
        ap_idle,
        ap_continue
);


input  [63:0] l_strA7_dout;
input   l_strA7_empty_n;
output   l_strA7_read;
input  [63:0] l_strB8_dout;
input   l_strB8_empty_n;
output   l_strB8_read;
output  [63:0] l_sum3_din;
input   l_sum3_full_n;
output   l_sum3_write;
input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_ready;
output   ap_idle;
input   ap_continue;

wire    tagAB_U0_ap_start;
wire    tagAB_U0_ap_done;
wire    tagAB_U0_ap_continue;
wire    tagAB_U0_ap_idle;
wire    tagAB_U0_ap_ready;
wire    tagAB_U0_start_out;
wire    tagAB_U0_start_write;
wire    tagAB_U0_l_strA7_read;
wire    tagAB_U0_l_strB8_read;
wire   [65:0] tagAB_U0_l_aStr1_din;
wire    tagAB_U0_l_aStr1_write;
wire   [63:0] tagAB_U0_l_bStr2_din;
wire    tagAB_U0_l_bStr2_write;
wire    systolicArray_U0_ap_start;
wire    systolicArray_U0_start_full_n;
wire    systolicArray_U0_ap_done;
wire    systolicArray_U0_ap_continue;
wire    systolicArray_U0_ap_idle;
wire    systolicArray_U0_ap_ready;
wire    systolicArray_U0_start_out;
wire    systolicArray_U0_start_write;
wire    systolicArray_U0_l_aStr1_read;
wire    systolicArray_U0_l_bStr2_read;
wire   [33:0] systolicArray_U0_l_dataA_0_din;
wire    systolicArray_U0_l_dataA_0_write;
wire   [33:0] systolicArray_U0_l_dataA_1_din;
wire    systolicArray_U0_l_dataA_1_write;
wire   [63:0] systolicArray_U0_l_dataB_0_din;
wire    systolicArray_U0_l_dataB_0_write;
wire    macs_U0_ap_start;
wire    macs_U0_start_out;
wire    macs_U0_start_write;
wire    macs_U0_l_dataA_0_read;
wire    macs_U0_l_dataB_0_read;
wire   [63:0] macs_U0_l_dataB_1_din;
wire    macs_U0_l_dataB_1_write;
wire   [63:0] macs_U0_l_sum_0_din;
wire    macs_U0_l_sum_0_write;
wire    macs_U0_ap_done;
wire    macs_U0_ap_ready;
wire    macs_U0_ap_idle;
wire    macs_U0_ap_continue;
wire    macs_1_U0_l_dataA_1_read;
wire    macs_1_U0_l_dataB_1_read;
wire   [63:0] macs_1_U0_l_sum_1_din;
wire    macs_1_U0_l_sum_1_write;
wire    macs_1_U0_ap_start;
wire    macs_1_U0_ap_done;
wire    macs_1_U0_ap_ready;
wire    macs_1_U0_ap_idle;
wire    macs_1_U0_ap_continue;
wire    merge_U0_ap_start;
wire    merge_U0_ap_done;
wire    merge_U0_ap_continue;
wire    merge_U0_ap_idle;
wire    merge_U0_ap_ready;
wire   [63:0] merge_U0_l_sum3_din;
wire    merge_U0_l_sum3_write;
wire    merge_U0_l_sum_0_read;
wire    merge_U0_l_sum_1_read;
wire    l_aStr_full_n;
wire   [65:0] l_aStr_dout;
wire   [1:0] l_aStr_num_data_valid;
wire   [1:0] l_aStr_fifo_cap;
wire    l_aStr_empty_n;
wire    l_bStr_full_n;
wire   [63:0] l_bStr_dout;
wire   [1:0] l_bStr_num_data_valid;
wire   [1:0] l_bStr_fifo_cap;
wire    l_bStr_empty_n;
wire    l_dataA_0_full_n;
wire   [33:0] l_dataA_0_dout;
wire   [2:0] l_dataA_0_num_data_valid;
wire   [2:0] l_dataA_0_fifo_cap;
wire    l_dataA_0_empty_n;
wire    l_dataA_1_full_n;
wire   [33:0] l_dataA_1_dout;
wire   [2:0] l_dataA_1_num_data_valid;
wire   [2:0] l_dataA_1_fifo_cap;
wire    l_dataA_1_empty_n;
wire    l_dataB_0_full_n;
wire   [63:0] l_dataB_0_dout;
wire   [2:0] l_dataB_0_num_data_valid;
wire   [2:0] l_dataB_0_fifo_cap;
wire    l_dataB_0_empty_n;
wire    l_dataB_1_full_n;
wire   [63:0] l_dataB_1_dout;
wire   [1:0] l_dataB_1_num_data_valid;
wire   [1:0] l_dataB_1_fifo_cap;
wire    l_dataB_1_empty_n;
wire    l_sum_0_full_n;
wire   [63:0] l_sum_0_dout;
wire   [1:0] l_sum_0_num_data_valid;
wire   [1:0] l_sum_0_fifo_cap;
wire    l_sum_0_empty_n;
wire    l_sum_1_full_n;
wire   [63:0] l_sum_1_dout;
wire   [1:0] l_sum_1_num_data_valid;
wire   [1:0] l_sum_1_fifo_cap;
wire    l_sum_1_empty_n;
wire   [0:0] start_for_systolicArray_U0_din;
wire    start_for_systolicArray_U0_full_n;
wire   [0:0] start_for_systolicArray_U0_dout;
wire    start_for_systolicArray_U0_empty_n;
wire   [0:0] start_for_macs_U0_din;
wire    start_for_macs_U0_full_n;
wire   [0:0] start_for_macs_U0_dout;
wire    start_for_macs_U0_empty_n;
wire   [0:0] start_for_macs_1_U0_din;
wire    start_for_macs_1_U0_full_n;
wire   [0:0] start_for_macs_1_U0_dout;
wire    start_for_macs_1_U0_empty_n;
wire   [0:0] start_for_merge_U0_din;
wire    start_for_merge_U0_full_n;
wire   [0:0] start_for_merge_U0_dout;
wire    start_for_merge_U0_empty_n;

cemit_replaced_tagAB tagAB_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(tagAB_U0_ap_start),
    .start_full_n(start_for_systolicArray_U0_full_n),
    .ap_done(tagAB_U0_ap_done),
    .ap_continue(tagAB_U0_ap_continue),
    .ap_idle(tagAB_U0_ap_idle),
    .ap_ready(tagAB_U0_ap_ready),
    .start_out(tagAB_U0_start_out),
    .start_write(tagAB_U0_start_write),
    .l_strA7_dout(l_strA7_dout),
    .l_strA7_num_data_valid(2'd0),
    .l_strA7_fifo_cap(2'd0),
    .l_strA7_empty_n(l_strA7_empty_n),
    .l_strA7_read(tagAB_U0_l_strA7_read),
    .l_strB8_dout(l_strB8_dout),
    .l_strB8_num_data_valid(2'd0),
    .l_strB8_fifo_cap(2'd0),
    .l_strB8_empty_n(l_strB8_empty_n),
    .l_strB8_read(tagAB_U0_l_strB8_read),
    .l_aStr1_din(tagAB_U0_l_aStr1_din),
    .l_aStr1_num_data_valid(l_aStr_num_data_valid),
    .l_aStr1_fifo_cap(l_aStr_fifo_cap),
    .l_aStr1_full_n(l_aStr_full_n),
    .l_aStr1_write(tagAB_U0_l_aStr1_write),
    .l_bStr2_din(tagAB_U0_l_bStr2_din),
    .l_bStr2_num_data_valid(l_bStr_num_data_valid),
    .l_bStr2_fifo_cap(l_bStr_fifo_cap),
    .l_bStr2_full_n(l_bStr_full_n),
    .l_bStr2_write(tagAB_U0_l_bStr2_write)
);

cemit_replaced_systolicArray systolicArray_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(systolicArray_U0_ap_start),
    .start_full_n(systolicArray_U0_start_full_n),
    .ap_done(systolicArray_U0_ap_done),
    .ap_continue(systolicArray_U0_ap_continue),
    .ap_idle(systolicArray_U0_ap_idle),
    .ap_ready(systolicArray_U0_ap_ready),
    .start_out(systolicArray_U0_start_out),
    .start_write(systolicArray_U0_start_write),
    .l_aStr1_dout(l_aStr_dout),
    .l_aStr1_num_data_valid(l_aStr_num_data_valid),
    .l_aStr1_fifo_cap(l_aStr_fifo_cap),
    .l_aStr1_empty_n(l_aStr_empty_n),
    .l_aStr1_read(systolicArray_U0_l_aStr1_read),
    .l_bStr2_dout(l_bStr_dout),
    .l_bStr2_num_data_valid(l_bStr_num_data_valid),
    .l_bStr2_fifo_cap(l_bStr_fifo_cap),
    .l_bStr2_empty_n(l_bStr_empty_n),
    .l_bStr2_read(systolicArray_U0_l_bStr2_read),
    .l_dataA_0_din(systolicArray_U0_l_dataA_0_din),
    .l_dataA_0_num_data_valid(l_dataA_0_num_data_valid),
    .l_dataA_0_fifo_cap(l_dataA_0_fifo_cap),
    .l_dataA_0_full_n(l_dataA_0_full_n),
    .l_dataA_0_write(systolicArray_U0_l_dataA_0_write),
    .l_dataA_1_din(systolicArray_U0_l_dataA_1_din),
    .l_dataA_1_num_data_valid(l_dataA_1_num_data_valid),
    .l_dataA_1_fifo_cap(l_dataA_1_fifo_cap),
    .l_dataA_1_full_n(l_dataA_1_full_n),
    .l_dataA_1_write(systolicArray_U0_l_dataA_1_write),
    .l_dataB_0_din(systolicArray_U0_l_dataB_0_din),
    .l_dataB_0_num_data_valid(l_dataB_0_num_data_valid),
    .l_dataB_0_fifo_cap(l_dataB_0_fifo_cap),
    .l_dataB_0_full_n(l_dataB_0_full_n),
    .l_dataB_0_write(systolicArray_U0_l_dataB_0_write)
);

cemit_replaced_macs macs_U0(
    .ap_start(macs_U0_ap_start),
    .start_full_n(start_for_merge_U0_full_n),
    .start_out(macs_U0_start_out),
    .start_write(macs_U0_start_write),
    .l_dataA_0_dout(l_dataA_0_dout),
    .l_dataA_0_empty_n(l_dataA_0_empty_n),
    .l_dataA_0_read(macs_U0_l_dataA_0_read),
    .l_dataB_0_dout(l_dataB_0_dout),
    .l_dataB_0_empty_n(l_dataB_0_empty_n),
    .l_dataB_0_read(macs_U0_l_dataB_0_read),
    .l_dataB_1_din(macs_U0_l_dataB_1_din),
    .l_dataB_1_full_n(l_dataB_1_full_n),
    .l_dataB_1_write(macs_U0_l_dataB_1_write),
    .l_sum_0_din(macs_U0_l_sum_0_din),
    .l_sum_0_full_n(l_sum_0_full_n),
    .l_sum_0_write(macs_U0_l_sum_0_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_done(macs_U0_ap_done),
    .ap_ready(macs_U0_ap_ready),
    .ap_idle(macs_U0_ap_idle),
    .ap_continue(macs_U0_ap_continue)
);

cemit_replaced_macs_1 macs_1_U0(
    .l_dataA_1_dout(l_dataA_1_dout),
    .l_dataA_1_empty_n(l_dataA_1_empty_n),
    .l_dataA_1_read(macs_1_U0_l_dataA_1_read),
    .l_dataB_1_dout(l_dataB_1_dout),
    .l_dataB_1_empty_n(l_dataB_1_empty_n),
    .l_dataB_1_read(macs_1_U0_l_dataB_1_read),
    .l_sum_1_din(macs_1_U0_l_sum_1_din),
    .l_sum_1_full_n(l_sum_1_full_n),
    .l_sum_1_write(macs_1_U0_l_sum_1_write),
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(macs_1_U0_ap_start),
    .ap_done(macs_1_U0_ap_done),
    .ap_ready(macs_1_U0_ap_ready),
    .ap_idle(macs_1_U0_ap_idle),
    .ap_continue(macs_1_U0_ap_continue)
);

cemit_replaced_merge merge_U0(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(merge_U0_ap_start),
    .ap_done(merge_U0_ap_done),
    .ap_continue(merge_U0_ap_continue),
    .ap_idle(merge_U0_ap_idle),
    .ap_ready(merge_U0_ap_ready),
    .l_sum3_din(merge_U0_l_sum3_din),
    .l_sum3_num_data_valid(2'd0),
    .l_sum3_fifo_cap(2'd0),
    .l_sum3_full_n(l_sum3_full_n),
    .l_sum3_write(merge_U0_l_sum3_write),
    .l_sum_0_dout(l_sum_0_dout),
    .l_sum_0_num_data_valid(l_sum_0_num_data_valid),
    .l_sum_0_fifo_cap(l_sum_0_fifo_cap),
    .l_sum_0_empty_n(l_sum_0_empty_n),
    .l_sum_0_read(merge_U0_l_sum_0_read),
    .l_sum_1_dout(l_sum_1_dout),
    .l_sum_1_num_data_valid(l_sum_1_num_data_valid),
    .l_sum_1_fifo_cap(l_sum_1_fifo_cap),
    .l_sum_1_empty_n(l_sum_1_empty_n),
    .l_sum_1_read(merge_U0_l_sum_1_read)
);

cemit_replaced_fifo_w66_d2_S l_aStr_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tagAB_U0_l_aStr1_din),
    .if_full_n(l_aStr_full_n),
    .if_write(tagAB_U0_l_aStr1_write),
    .if_dout(l_aStr_dout),
    .if_num_data_valid(l_aStr_num_data_valid),
    .if_fifo_cap(l_aStr_fifo_cap),
    .if_empty_n(l_aStr_empty_n),
    .if_read(systolicArray_U0_l_aStr1_read)
);

cemit_replaced_fifo_w64_d2_S_x0 l_bStr_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(tagAB_U0_l_bStr2_din),
    .if_full_n(l_bStr_full_n),
    .if_write(tagAB_U0_l_bStr2_write),
    .if_dout(l_bStr_dout),
    .if_num_data_valid(l_bStr_num_data_valid),
    .if_fifo_cap(l_bStr_fifo_cap),
    .if_empty_n(l_bStr_empty_n),
    .if_read(systolicArray_U0_l_bStr2_read)
);

cemit_replaced_fifo_w34_d4_S l_dataA_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolicArray_U0_l_dataA_0_din),
    .if_full_n(l_dataA_0_full_n),
    .if_write(systolicArray_U0_l_dataA_0_write),
    .if_dout(l_dataA_0_dout),
    .if_num_data_valid(l_dataA_0_num_data_valid),
    .if_fifo_cap(l_dataA_0_fifo_cap),
    .if_empty_n(l_dataA_0_empty_n),
    .if_read(macs_U0_l_dataA_0_read)
);

cemit_replaced_fifo_w34_d4_S l_dataA_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolicArray_U0_l_dataA_1_din),
    .if_full_n(l_dataA_1_full_n),
    .if_write(systolicArray_U0_l_dataA_1_write),
    .if_dout(l_dataA_1_dout),
    .if_num_data_valid(l_dataA_1_num_data_valid),
    .if_fifo_cap(l_dataA_1_fifo_cap),
    .if_empty_n(l_dataA_1_empty_n),
    .if_read(macs_1_U0_l_dataA_1_read)
);

cemit_replaced_fifo_w64_d4_S l_dataB_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(systolicArray_U0_l_dataB_0_din),
    .if_full_n(l_dataB_0_full_n),
    .if_write(systolicArray_U0_l_dataB_0_write),
    .if_dout(l_dataB_0_dout),
    .if_num_data_valid(l_dataB_0_num_data_valid),
    .if_fifo_cap(l_dataB_0_fifo_cap),
    .if_empty_n(l_dataB_0_empty_n),
    .if_read(macs_U0_l_dataB_0_read)
);

cemit_replaced_fifo_w64_d2_S_x0 l_dataB_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(macs_U0_l_dataB_1_din),
    .if_full_n(l_dataB_1_full_n),
    .if_write(macs_U0_l_dataB_1_write),
    .if_dout(l_dataB_1_dout),
    .if_num_data_valid(l_dataB_1_num_data_valid),
    .if_fifo_cap(l_dataB_1_fifo_cap),
    .if_empty_n(l_dataB_1_empty_n),
    .if_read(macs_1_U0_l_dataB_1_read)
);

cemit_replaced_fifo_w64_d2_S_x0 l_sum_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(macs_U0_l_sum_0_din),
    .if_full_n(l_sum_0_full_n),
    .if_write(macs_U0_l_sum_0_write),
    .if_dout(l_sum_0_dout),
    .if_num_data_valid(l_sum_0_num_data_valid),
    .if_fifo_cap(l_sum_0_fifo_cap),
    .if_empty_n(l_sum_0_empty_n),
    .if_read(merge_U0_l_sum_0_read)
);

cemit_replaced_fifo_w64_d2_S_x0 l_sum_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(macs_1_U0_l_sum_1_din),
    .if_full_n(l_sum_1_full_n),
    .if_write(macs_1_U0_l_sum_1_write),
    .if_dout(l_sum_1_dout),
    .if_num_data_valid(l_sum_1_num_data_valid),
    .if_fifo_cap(l_sum_1_fifo_cap),
    .if_empty_n(l_sum_1_empty_n),
    .if_read(merge_U0_l_sum_1_read)
);

cemit_replaced_start_for_systolicArray_U0 start_for_systolicArray_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_systolicArray_U0_din),
    .if_full_n(start_for_systolicArray_U0_full_n),
    .if_write(tagAB_U0_start_write),
    .if_dout(start_for_systolicArray_U0_dout),
    .if_empty_n(start_for_systolicArray_U0_empty_n),
    .if_read(systolicArray_U0_ap_ready)
);

cemit_replaced_start_for_macs_U0 start_for_macs_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_macs_U0_din),
    .if_full_n(start_for_macs_U0_full_n),
    .if_write(systolicArray_U0_start_write),
    .if_dout(start_for_macs_U0_dout),
    .if_empty_n(start_for_macs_U0_empty_n),
    .if_read(macs_U0_ap_ready)
);

cemit_replaced_start_for_macs_1_U0 start_for_macs_1_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_macs_1_U0_din),
    .if_full_n(start_for_macs_1_U0_full_n),
    .if_write(systolicArray_U0_start_write),
    .if_dout(start_for_macs_1_U0_dout),
    .if_empty_n(start_for_macs_1_U0_empty_n),
    .if_read(macs_1_U0_ap_ready)
);

cemit_replaced_start_for_merge_U0 start_for_merge_U0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .if_read_ce(1'b1),
    .if_write_ce(1'b1),
    .if_din(start_for_merge_U0_din),
    .if_full_n(start_for_merge_U0_full_n),
    .if_write(macs_U0_start_write),
    .if_dout(start_for_merge_U0_dout),
    .if_empty_n(start_for_merge_U0_empty_n),
    .if_read(merge_U0_ap_ready)
);

assign ap_done = merge_U0_ap_done;

assign ap_idle = (tagAB_U0_ap_idle & systolicArray_U0_ap_idle & merge_U0_ap_idle & macs_U0_ap_idle & macs_1_U0_ap_idle);

assign ap_ready = tagAB_U0_ap_ready;

assign l_strA7_read = tagAB_U0_l_strA7_read;

assign l_strB8_read = tagAB_U0_l_strB8_read;

assign l_sum3_din = merge_U0_l_sum3_din;

assign l_sum3_write = merge_U0_l_sum3_write;

assign macs_1_U0_ap_continue = 1'b1;

assign macs_1_U0_ap_start = start_for_macs_1_U0_empty_n;

assign macs_U0_ap_continue = 1'b1;

assign macs_U0_ap_start = start_for_macs_U0_empty_n;

assign merge_U0_ap_continue = ap_continue;

assign merge_U0_ap_start = start_for_merge_U0_empty_n;

assign start_for_macs_1_U0_din = 1'b1;

assign start_for_macs_U0_din = 1'b1;

assign start_for_merge_U0_din = 1'b1;

assign start_for_systolicArray_U0_din = 1'b1;

assign systolicArray_U0_ap_continue = 1'b1;

assign systolicArray_U0_ap_start = start_for_systolicArray_U0_empty_n;

assign systolicArray_U0_start_full_n = (start_for_macs_U0_full_n & start_for_macs_1_U0_full_n);

assign tagAB_U0_ap_continue = 1'b1;

assign tagAB_U0_ap_start = ap_start;

endmodule //cemit_replaced_process_r
